version: '3.8'

services:
  star-sn:
    build:
      context: .
    ports:
      - '8000:8000'
    command: ['sh', './run.sh']
    volumes:
      - .:/app

    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/posgresql/data
    environment:
      POSTGRES_USER: social_admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: social_db
      POSTGRES_HOST: db
    ports:
      - "${DB_PORT:-5432}:5432"

volumes:
  postgres_data:
