# Generated by Django 4.2.6 on 2023-10-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, db_column='DATE')),
            ],
            options={
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='TITLE', max_length=100)),
                ('content', models.TextField(db_column='CONTENT')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='DATE')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
