# Generated by Django 4.2.6 on 2023-10-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_like_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTagRelations',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
